# Copyright 2025 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example Ferris Sweep with ZMK Studio'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2","nice_nano_v2"]'
      shield: '["cradio_left","cradio_right"]'
      nav: '["invertedt"]'
      clipboard: '["mac"]'
      kconfig: '["CONFIG_ZMK_STUDIO=y\nCONFIG_BT_BAS=y\nCONFIG_ZMK_BATTERY_REPORTING=y\nCONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y\nCONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y\nCONFIG_BT_CTLR_TX_PWR_PLUS_8=y
      # Note: ZMK Studio snippet only applied to left (central) side
      # Battery levels for both halves will be reported via BLE
